### ISSUE TITLE
Confirmation on remove parameter

### ISSUE THREAD

**Issue by RX14** [rhaamo/StockazIO#150]
This button is too easy to click by accident!

![](https://stephanie.is/jizoj-tatar)

It'd be nice if there was a confirmation, if any of the fields aren't blank

**Comment by rhaamo** [comment]
I can do it like delete part, with a modal, would that be ok ?

**Comment by RX14** [comment]
yeah, sure

**Comment by rhaamo** [comment]
modals are too intrusive for that usage, so I've implemented a smol component that pops two buttons that have to be explicitely clicked after clicking the main one.

![Enregistrement de l’écran 2020-12-06 à 08 17 26](https://user-images.githubusercontent.com/8625/101274115-b4572280-379b-11eb-8735-e891b1ef3753.gif)
