### ISSUE TITLE
Some kind of autocomplete on part parameters

### ISSUE THREAD

**Issue by RX14** [rhaamo/StockazIO#151]
For anything in the resistor category you're gonna want to fill in resistance, tolerance, power rating, etc. I'd rather not have the chance to mis-spell these

Not sure the best way to do this, whether to put a list of common parameters in the DB, or somehow autocomplete common ones. Browser autocomplete helps a little

Having them in the DB means you could set a list of them to filter on per-category, similar to the filters at the top on farnell, mouser, etc. Also means you could specify a default unit for them so you didn't have to fill that in (better handling of SI input would be nice)

**Comment by rhaamo** [comment]
Autocompletion shouldn't be much of an issue, having pre-defined sets per categories would be more.

I guess I could make a form with choice for a category, and adding sets of `name` and `unit` to that 'part parameters presets', which would auto-create the parameters table.

As for SI units, I don't know, tbh I don't (yet) much uses the part parameters

**Comment by RX14** [comment]
I'm fine with autocompletion, having a preset list of parameters for each category would be awesome!

I use part parameters for everything tbh, I'm anticipating the ability to filter on them in the future so I'll be able to choose the resistors category, and look in a table at all the values I have (again, like distributors)

SI units would be great, for example entering 50k to get 50kohm, instead of 50, and then having to find kohm in the units list

also, for example, correcting 0.1uF to 100nF

**Comment by rhaamo** [comment]
I will do autocompletion first, and think about presets after that.

As for filtering on part parameters that should be doable through the rest api, I'm not sure yet how that could be nicely implemented in the frontend. (the whole filtering part should be re-done anyway)

**Comment by RX14** [comment]
Thinking more about autocompletion - would be nice to autocomplete description when you autocomplete a name. But descriptions can differ for the same name...

I like the "name" "description" pair btw, I can do "Vds" "Max Drain-Source Voltage" without having to shove it in as "Drain-source voltage Vds" like farnell does.

**Comment by rhaamo** [comment]
so hm bouncing on that, I'm thinking of two things:

## 1
having a dedicated "part parameters presets", which can allows to make templates with:
- name (required)
- description (opt)
- unit (opt)

And in add part / edit, part parameters, adding a dropdown "apply preset" which will add all items from the preset, you would just have to fill in the values, and perhaps adapt the unit for /that/ part

## 2
part parameters and preset could have auto-completion for name and description, starting to type would autocomplete from all name or desc found in the DB

## 3
removing of labels in part parameters (at least) and moving them to placeholders for less space usage

what do you think ?
