### ISSUE TITLE
Datasheet URL for parts

### ISSUE THREAD

**Issue by RX14** [rhaamo/StockazIO#152]
This would be nice, could even automate it from for example a farnell part number, or a TI part name cause they have consistent URLs

The last bit could be a bit flakey though so it's best to use that as an autocomplete

The URL is likely to bitrot over time though, knowing manufacturers

**Comment by rhaamo** [comment]
Would using the part attachment and giving an URL works ?

IIRC it's possible to do that with the django upload thing, just not implemented in frontend.

**Comment by RX14** [comment]
I'd rather store URLs which will always go to the latest datasheet revision than reupload PDFs

**Comment by rhaamo** [comment]
it could be possible to generate a link if there is a part manufacturer == TI or part distributor == farnell, if generating a link with only the SKU is possible. if not that would have to be done with a supplementary URL field to any of thoses.

**Comment by RX14** [comment]
Yeah, I think it's best to do something like store a URL field for datasheets, but auto-fill the field if you entered a manufacturer or distributor with a known URL pattern

often you have to knock a few digits off the end of the part number to get the datasheet from TI etc, so it's more useful to have these as a completion aid...

**Comment by rhaamo** [comment]
Ok for TI URLs are like
```
https://www.ti.com/lit/ds/symlink/bq2970.pdf
https://www.ti.com/lit/ds/symlink/lp38691.pdf
```
so it's not much of an issue to "auto generate" them

however, for farnell they seems to be an ID unrelated to the SKU of manufacturer or farnell :(

**Comment by rhaamo** [comment]
So that's what I was thinking about.
Handled placeholders are `{sku}` and `_lower` or `_upper`, thoses ones are auto-set from the manufacturer sku, there is also `{_}` which does nothing.

Demo video: https://tube.otter.sh/videos/watch/d7931549-8996-45c4-abbb-864caa4c6fc4

Does that correspond to what you need ?

**Comment by RX14** [comment]
Yeah that's awesome! Thanks
