### ISSUE TITLE
Better handling of SI prefixed units

### ISSUE THREAD

**Issue by RX14** [rhaamo/StockazIO#224]
Currently there are multiple units for each prefix-unit combo

This has some weird display issues (https://stephanie.is/nomad-vunub), and it also makes sorting parts based on that parameter more tricky than it should be.

Normalizing display of units would be neat too (for example 0.1uF gets converted to 100nF because they're stored as 1e-7F

**Comment by rhaamo** [comment]
OK so what I can do:
- Change the default seeds `part parameter unit` to only 'volt', 'amperes' etc. with only `name` and `symbol`
	- Add a *custom* data migration to properly dedup the table when the default seeds has been used
- Users can fill `10u` in part parameter and select `amperes` and it will be displayed as `valueSymbol` like `10uA`

**Comment by RX14** [comment]
yeah, that'd be a really nice design!

**Comment by rhaamo** [comment]
![image](https://user-images.githubusercontent.com/8625/117563863-f8cb4f00-b0a8-11eb-8567-0fd33ff1aa0b.png)
![image](https://user-images.githubusercontent.com/8625/117563874-08e32e80-b0a9-11eb-9ec7-8d3e53485699.png)

**Comment by rhaamo** [comment]
should I make parameter units Name and Symbol uniques, or only Name (or symbol) ?

**Comment by RX14** [comment]
probably both?

**Comment by rhaamo** [comment]
yeah I've thought about that but I do wonder if there might be units with the same symbol existing

**Comment by RX14** [comment]
perhaps, can always change it later to remove the unique - it's harder to make it unique after not being

**Comment by rhaamo** [comment]
right, worst case if it happens, I will switch from unique of both separately to a combined unique
