### ISSUE TITLE
Entry form streamlining

### ISSUE THREAD

**Issue by MightyPork** [rhaamo/StockazIO#366]
Common flow:

1. enter new part
  - find out the category you wanted is missing
2. attach datasheet or footprint
3. add picture

Now it's kind of cumbersome:

1. create new category in category editor (ok, front-end category editing isn't added yet, this works)
2. enter the new part's basic parameters
   - scroll to the bottom because the form is very long lol
3. find the part using search or in categories
4. click its name (not actions/edit, it isn't there)
5. click "Show full details" in the modal
6. add attachments as needed

My ideas for improvements:

- allow attaching files right in the "new part" form
- or, have 2 save buttons - "Save and Add More" and "Save" (then goes to the new part's page so you can upload files)
- allow to manage files in the edit form, not only in "Full details"
  - it's now kind of reversed, you can edit files in the details page but not in edit
- ~make fields in the "new part" form configurable so it's not as long (possibly also hide them in other places). I only use like 4 of the fields.~ split to own issue
- ~Dedicated photo attachment (some magic value as name?) so it shows as picture in the details page, you could then also have a grid view with part photos, that would be cool~ split to own issue

**Comment by rhaamo** [comment]
- Adding file management in Add Full should be possible
- Possible too
- Can add to edit I guess too, or avoid that by implementing "save" alongside actual "save and add more"
- The quick add is here to avoid the full entry workflow, custom forms could be possible, but it's way too much work that what I would want to do
- files detected as pictures, lets say limited to 4 or 5, could be shown on details view right under the description, that shouldn't be very hard to make, a "default" one should be possible I guess too, the default could be shown within a tooltip using a picture icon on the left of the part name in listings too

**Comment by MightyPork** [comment]
ok i made new issues for the last two points.

Really any way of the 3 ways to attach a file would be good.

attaching right in the form may have a problem that you don't have an ID yet, i think the easiest way is to have the two buttons

**Comment by rhaamo** [comment]
the ID isn't much of an issue, because it's handled a bit manually by the backend.

tbh I am more interested in doing a save/save and add more, plus adding the fields in edit if I can

**Comment by rhaamo** [comment]
I have added save and view & save and add more in bbf3c81

Default is 'save and view', should it be the other one or it's fine ?

**Comment by MightyPork** [comment]
The form is good! Much easier to add files now.

Search and the home page's list of parts stopped working after I pulled, though. The content area is just white.

url like `/parts?q=esp8266`

```
vue.runtime.esm.js:1897 TypeError: Cannot read properties of undefined (reading 'id')
    at o.br (List.vue?9c59:1:753)
    at o.e._render (vue.runtime.esm.js:3569:22)
    at o.n (vue.runtime.esm.js:4081:21)
    at rn.get (vue.runtime.esm.js:4495:25)
    at new rn (vue.runtime.esm.js:4484:12)
    at Tr (vue.runtime.esm.js:4088:3)
    at o.Cn.$mount (vue.runtime.esm.js:8459:10)
    at init (vue.runtime.esm.js:3137:13)
    at r (vue.runtime.esm.js:3322:5)
    at f (vue.runtime.esm.js:6022:9)
```

**Comment by rhaamo** [comment]
fixed

**Comment by MightyPork** [comment]
yup its good now!

**Comment by rhaamo** [comment]
going to consider this one done.
managing part files in edit isn't yet planned as it will requires changes in the backend (it's a standalone endpoint)
