### ISSUE TITLE
Storage editor broken

### ISSUE THREAD

**Issue by MightyPork** [rhaamo/StockazIO#368]
add root category

![Screenshot_20220214_204035](https://user-images.githubusercontent.com/2041118/153934620-f8ec0d48-fdd9-469b-af0a-ad1e3c8827b0.png)

add storage box

![Screenshot_20220214_204003](https://user-images.githubusercontent.com/2041118/153934642-da042472-617c-44ae-85a0-228c9036108c.png)

![Screenshot_20220214_204018](https://user-images.githubusercontent.com/2041118/153934654-b2d30300-ff37-40b9-8d5d-f9f578a23b10.png)

add category

also 403

**Comment by rhaamo** [comment]
I wonder if it's because of the storage scope in the oauth thing I have introduced. it is still an issue after using logout then login ?

**Comment by MightyPork** [comment]
tried logout and login and still same.

its the first account, admin, probably

**Comment by rhaamo** [comment]
lol i had removed the scopes from the front at some point, I have reverted the scopes in the backend, try updating and restarting the backend

**Comment by MightyPork** [comment]
add root category still doesnt work, but the 403 is fixed :+1:

**Comment by rhaamo** [comment]
what error do you have with the root ?

**Comment by rhaamo** [comment]
ok no modal, let me see

**Comment by rhaamo** [comment]
should be fixed by 69ce287

**Comment by MightyPork** [comment]
yes its good now
