### ISSUE TITLE
Feature: Part photos/pictures

### ISSUE THREAD

**Issue by MightyPork** [rhaamo/StockazIO#371]
Dedicated photo attachment (some magic value as name?) so it shows as picture in the details page, you could then also have a grid view with part photos, that would be cool

maybe this could also be switched to show instead of QR codes if someone doesn't need QR codes

**Comment by rhaamo** [comment]
files detected as pictures, lets say limited to 4 or 5, could be shown on details view right under the description, that shouldn't be very hard to make, a "default" one should be possible I guess too, the default could be shown within a tooltip using a picture icon on the left of the part name in listings too

**Comment by rhaamo** [comment]
About adding file attachments to 'Edit' I have to see, the file attachment API is a standalone endpoint to simplify stuff.
Rest of the features can still be implemented.

**Comment by rhaamo** [comment]
Will be handled in #374

**Comment by rhaamo** [comment]
and it is going to be more annoying that expected because we handle uploading of various pdf/text files and not only images

**Comment by rhaamo** [comment]
Implemented in #374
