### ISSUE TITLE
Feature: Edit multiple parts

### ISSUE THREAD

**Issue by MightyPork** [rhaamo/StockazIO#373]
![Screenshot_20220214_213656](https://user-images.githubusercontent.com/2041118/153942487-87972c12-e540-48d8-9737-b107e65f62e1.png)

then click a button and a modal opens where you can do some things to the selected parts, like:

- set category
- set location
- delete all selected
- other things that make sense in bulk

**Comment by rhaamo** [comment]
I have to think about that, It should be possible with items from current page, doing things like 'select everything' might not be that easy
Need to think how to integrate it to the UI too

**Comment by rhaamo** [comment]
bulk edit (from current page) have been implemented with: delete, change location, change storage
