### ISSUE TITLE
photo bugs

### ISSUE THREAD

**Issue by MightyPork** [rhaamo/StockazIO#380]
- files that already existed when the photos feature was added are not recognized as photos. it's fixed by reupload.  (nbd, i have only 5 photos added)
-  the "part detail modal" lacks photo previews but also photo file links (the "link" is not clickable)

![Screenshot_20220216_115513](https://user-images.githubusercontent.com/2041118/154250410-3536c562-11fd-40d4-92fb-18bd8bb382f3.png)

- can't unclick "default photo" checkbox if there's only one photo (is this needed? idk)

**Comment by rhaamo** [comment]
haven't thought about existing files oops

indeed not implemented in details, will do

I didn't managed the "only one picture" case, I could try

**Comment by rhaamo** [comment]
part details modal now have them
![image](https://user-images.githubusercontent.com/8625/154547951-a9477bfc-59e3-45b3-89ac-90c994a85006.png)

rest will be worked on next

**Comment by rhaamo** [comment]
if you still have uploads to migrate: `python manage.py migrations_move_from_one_to_two_part_file_fields`

**Comment by MightyPork** [comment]
migration works great, thanks for adding that!

also it's MUCH faster now :tada:

**Comment by rhaamo** [comment]
yes preloaded datas are now stored in localstorage and refreshed wheen needed or every 24.

for the "default picture" I have handledit in frontend. if no default picture, the first one will be shown as default so there is always one preview on the list.
