### ISSUE TITLE
bulk edit bugs

### ISSUE THREAD

**Issue by MightyPork** [rhaamo/StockazIO#390]
small issues just so i dont forget

- change location 
  - lets you pick a category instead of location, it then fails with 500
  - no way to bulk remove location
- buttons are very big and wrap without spacing

![Screenshot_20220219_175303](https://user-images.githubusercontent.com/2041118/154810530-d5c2ef55-c39f-45e4-9a81-f73b51211355.png)

- too big z index

![Screenshot_20220219_175428](https://user-images.githubusercontent.com/2041118/154810584-8ccd778b-1e6d-4249-be30-6a41c2e335de.png)

**Comment by rhaamo** [comment]
can you tell me if it's better about the spacing and not-closing ?

what do you mean pick a category instead of location ?

**Comment by MightyPork** [comment]
spacing is great, auto-closing too.

new bug, you cant select anything, it closes after you click the dropdown :see_no_evil: 

about selecting category, if you have a storage kind (Boxes) and no box added yet, you can click Boxes and it lets you select that as if it was a storage location. Once you have some boxes added, this bug no longer appears

oh one tiny improvement i just thought of, the buttons should be disabled until something is selected if thats not too complicated to add. Now you get a js error if you submit the form and nothing is selected.

```
TypeError: Cannot read properties of undefined (reading '$refs')
    at o.getMenu (chunk-vendors.e6cc6746.js:64:19065)
    at onBlur (chunk-vendors.e6cc6746.js:64:31486)
    at nt (chunk-vendors.e6cc6746.js:12:11674)
    at HTMLInputElement.r (chunk-vendors.e6cc6746.js:12:13494)
    at HTMLInputElement.a._wrapper (chunk-vendors.e6cc6746.js:12:52151)
    at Object.vi [as removeChild] (chunk-vendors.e6cc6746.js:12:42453)
    at h (chunk-vendors.e6cc6746.js:12:44111)
    at r (chunk-vendors.e6cc6746.js:12:44039)
    at chunk-vendors.e6cc6746.js:12:59187
    at chunk-vendors.e6cc6746.js:12:2541
```

**Comment by rhaamo** [comment]
yes auto-closing will means you have to select then use the buttons.

will fix the rest of the issues later.

**Comment by MightyPork** [comment]
no there's something funny happening here

https://user-images.githubusercontent.com/2041118/154817876-134b1e86-2ace-43f3-b5cf-44a1478cbf89.mp4

**Comment by rhaamo** [comment]
yep I have fixed that by changing the method for closing.

the remaining issue is that I need to manage to filter the tree to remove child-less categories

**Comment by rhaamo** [comment]
everything should be fixed

**Comment by MightyPork** [comment]
yeah good now :+1:
