### ISSUE TITLE
[bug] changing category on page 2 shows page 1 but paginator stays at page 2

### ISSUE THREAD

**Issue by MightyPork** [rhaamo/StockazIO#402]
1. go to page 2 of a part listing
2. use bulk edit to change some parts' category
3. bug ensues

**Comment by rhaamo** [comment]
I can't reproduce on my side

**Comment by rhaamo** [comment]
oh wait you were talking about the paginator, I see

**Comment by rhaamo** [comment]
fixed, the fetch will now set the right current page

**Comment by MightyPork** [comment]
confirmed :+1:
