### ISSUE TITLE
Minor bugs with new frontend

### ISSUE THREAD

**Issue by RX14** [rhaamo/StockazIO#599]
- A way to "Download Labels PDF" has been removed from the label generator dialog. There are problems with using certain drivers with the browser print dialog, which doesn't send the PDF to the printer unmodified.
- When filtering parts by storage, you have to choose the storage then choose "equals". It seems like "equals" should be the default, and the search should be done as soon as you select (or change) the item in the storage box.

**Comment by rhaamo** [comment]
Should be fixed with the last two commits!
