### ISSUE TITLE
Cannot import name 'save_virtual_workbook' from 'openpyxl.writer.excel'

### ISSUE THREAD

**Issue by ereenke** [rhaamo/StockazIO#617]
Installation breaks with the following error:

`ImportError: cannot import name 'save_virtual_workbook' from 'openpyxl.writer.excel' (/home/stockazio/stockazio/venv/lib/python3.10/site-packages/openpyxl/writer/excel.py)`

I found a solution to this problem on [stackoverflow](https://stackoverflow.com/questions/75299506/cannot-import-name-save-virtual-workbook-from-openpyxl-writer-excel): `pip install openpyxl==3.0.10`

**Comment by rhaamo** [comment]
looks like one dependency might have not pinned `openpyxl`, I will look at updating everything soon.

thanks!
